image: hashicorp/terraform:1.3.0

stages:
  - plan
  - apply

variables:
  TF_IN_AUTOMATION: "true"
  TF_CLI_ARGS: "-no-color"
  TF_WORKING_DIR: "./terraform"

before_script:
  - cd $TF_WORKING_DIR
  - terraform init

terraform_plan:
  stage: plan
  script:
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - $TF_WORKING_DIR/tfplan
    expire_in: 1 hour
  only:
    - main
    - merge_requests

terraform_apply:
  stage: apply
  script:
    - terraform apply -auto-approve tfplan
  when: manual  # Requires manual approval
  dependencies:
    - terraform_plan
  only:
    - main

